### ISSUE TITLE
[Feature Request] Optionally configure owner teams' approval

### ISSUE THREAD

**Issue by natale-p** [skymoore/required-approvals#10]
Hello, 

sometimes CODEOWNERS specify multiple teams owning a directory:
```
only-sparta/**         @Sparta
this-is-shared/**    @Sparta @Athens
```

However, there are situations in which one approval, given that is coming from one of the owning's teams, is enough. Logically, that would be an OR between the owners, instead of an AND. There is a way to configure this?

Thanks in advance

**Comment by skymoore** [comment]
Hi @natale-p! Thank you for the feature request.  I will take a deeper look in the coming week as I'm presently on vacation.

**Comment by AlvaroGG0** [comment]
This feature would be a nice to have!
