### ISSUE TITLE
Patterns for files in repo root are no longer matched

### ISSUE THREAD

**Issue by druchoo** [skymoore/required-approvals#19]
The following changes seem to break evaluating patterns for files in the repo's root:
- https://github.com/skymoore/required-approvals/commit/7e7485f950f21f8193a0b84356eaa8b2d18b1925
- https://github.com/skymoore/required-approvals/commit/cea0d9302a2c7efbad8a0cfb71057847373180da
- https://github.com/skymoore/required-approvals/commit/52be6a1682d357485519c99833a44f56beaf56a0

For example, with a `CODEOWNERS` file as follows, the `my-file` file is not matched.

```
my-file @MyOrg/my-team
```

The file will match both if conditions (https://github.com/skymoore/required-approvals/blob/main/src/index.js#L52-L57) and set pattern to `my-file/**` and changedFile to `/my-file`. [minimatch](https://www.npmjs.com/package/minimatch/v/5.1.0#minimatchpath-pattern-options) then fails to match.

```js
minimatch("/my-file", "my-file/**", { dot: true })
```

Converting https://github.com/skymoore/required-approvals/blob/main/src/index.js#L52-L57 to an if/else would fix but I'm not sure if that is best approach.

**Comment by skymoore** [comment]
@AlvaroGG0 I'm going to take a look at this, would appreciate your input as well.

**Comment by skymoore** [comment]
@druchoo Thanks for submitting this.  Will get it sorted.

**Comment by skymoore** [comment]
@druchoo check [v4.2.5](https://github.com/skymoore/required-approvals/releases/tag/v4.2.5) please.

**Comment by skymoore** [comment]
@AlvaroGG0 Thank you for the PR!

**Comment by skymoore** [comment]
@druchoo @AlvaroGG0 Closing this one since no complaints after last PR.
