### ISSUE TITLE
Only 30 Org Teams are processed

### ISSUE THREAD

**Issue by druchoo** [skymoore/required-approvals#7]
By default on 30 Org Teams are processed and the rest are ignored.

> All endpoint methods starting with .list* do not return all results at once but instead return the first 30 items by default, see also [GitHub’s REST API pagination documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#pagination).

https://octokit.github.io/rest.js/v20#pagination

https://github.com/skymoore/required-approvals/pull/6 to fix

**Comment by skymoore** [comment]
Hi @druchoo.  I appreciate you filing this issue and am reviewing the PR.  Will get this merged in and cut a new release tomorrow.

**Comment by skymoore** [comment]
@druchoo [v4.0.1](https://github.com/skymoore/required-approvals/releases/tag/v4.0.1) is out.  Thanks again.

@vistrcm don't think this affects you, but wanted you to be aware.
