### ISSUE TITLE
Execution time can be slow when there are a large number of teams in the Org

### ISSUE THREAD

**Issue by druchoo** [skymoore/required-approvals#9]
Hello @skymoore,

Thanks for releasing https://github.com/skymoore/required-approvals/pull/6. The change works as expected but increases execution time when there are many teams.

For about 300 teams, I am seeing execution times of 2+ minutes for the Action.

Can you review https://github.com/skymoore/required-approvals/pull/8 for a proposed solution? 

Thanks

**Comment by skymoore** [comment]
@druchoo Yes, I will take a look.  Thank you.

**Comment by skymoore** [comment]
@druchoo [v4.1.0](https://github.com/skymoore/required-approvals/releases/tag/v4.1.0) ready to go.  Thanks again for improving this action.
